# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flows_network_v1.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'flows_network_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66lows_network_v1.proto\x12/com.ptvgroup.archimedes.api.protobuf.network.v1\"\x8c\x01\n\x07Network\x12\x13\n\x0bmap_version\x18\x01 \x01(\t\x12#\n\x1b\x63oordinate_reference_system\x18\x02 \x01(\t\x12G\n\x06street\x18\x03 \x03(\x0b\x32\x37.com.ptvgroup.archimedes.api.protobuf.network.v1.Street\"\xa9\x01\n\x06Street\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x66rom_node_id\x18\x02 \x01(\x05\x12\x0e\n\x06openlr\x18\x03 \x01(\x0c\x12\x1d\n\x15\x66unctional_road_class\x18\x04 \x01(\x05\x12\x13\n\x0b\x66orm_of_way\x18\x05 \x01(\x05\x12\x1c\n\x14\x66ree_flow_speed_kmph\x18\x06 \x01(\x01\x12\r\n\x05shape\x18\x07 \x01(\x0c\x12\x0c\n\x04name\x18\x08 \x01(\tBM\n/com.ptvgroup.archimedes.api.protobuf.network.v1\xaa\x02\x19PTVGroup.Flows.Protos.APIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flows_network_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.ptvgroup.archimedes.api.protobuf.network.v1\252\002\031PTVGroup.Flows.Protos.API'
  _globals['_NETWORK']._serialized_start=76
  _globals['_NETWORK']._serialized_end=216
  _globals['_STREET']._serialized_start=219
  _globals['_STREET']._serialized_end=388
# @@protoc_insertion_point(module_scope)
