# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: street_forecast.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'street_forecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15street_forecast.proto\x12\x30\x63om.ptvgroup.mlf.common.messagehandling.forecast\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x03\n\x0c\x46orecastData\x12\x65\n\x0estreetForecast\x18\x01 \x03(\x0b\x32M.com.ptvgroup.mlf.common.messagehandling.forecast.ForecastData.StreetForecast\x1a\x9d\x01\n\x0eStreetForecast\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66romNode\x18\x02 \x01(\x05\x12Y\n\x08\x66orecast\x18\x03 \x03(\x0b\x32G.com.ptvgroup.mlf.common.messagehandling.forecast.ForecastData.Forecast\x12\x12\n\nopenLRcode\x18\x04 \x01(\t\x1a\xb6\x01\n\x08\x46orecast\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nflow_valid\x18\x03 \x01(\x08\x12\x0c\n\x04\x66low\x18\x04 \x01(\x01\x12\x13\n\x0bspeed_valid\x18\x05 \x01(\x08\x12\r\n\x05speed\x18\x06 \x01(\x01\x12\x10\n\x08timezone\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'street_forecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTDATA']._serialized_start=109
  _globals['_FORECASTDATA']._serialized_end=571
  _globals['_FORECASTDATA_STREETFORECAST']._serialized_start=229
  _globals['_FORECASTDATA_STREETFORECAST']._serialized_end=386
  _globals['_FORECASTDATA_FORECAST']._serialized_start=389
  _globals['_FORECASTDATA_FORECAST']._serialized_end=571
# @@protoc_insertion_point(module_scope)
