# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataprv_traffic_realtime_data.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'dataprv_traffic_realtime_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#dataprv_traffic_realtime_data.proto\x12\x43\x63om.ptvgroup.archimedes.dataprv.protobuf.traffic.realtime.output.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x02\n\x1f\x44\x61taprvTrafficRealtimeDataProto\x12\x10\n\x08timezone\x18\x01 \x01(\t\x12\x36\n\x12snapshot_date_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x8a\x01\n\x0estreet_traffic\x18\x03 \x03(\x0b\x32r.com.ptvgroup.archimedes.dataprv.protobuf.traffic.realtime.output.v1.DataprvTrafficRealtimeDataProto.StreetTraffic\x1aq\n\rStreetTraffic\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x66rom_node_id\x18\x02 \x01(\x05\x12\x11\n\tspeed_kmh\x18\x03 \x01(\x01\x12\x13\n\x0bprobe_count\x18\x05 \x01(\x05\x12\x10\n\x08olr_code\x18\x06 \x01(\tJ\x04\x08\x04\x10\x05\x42\x9e\x01\nCcom.ptvgroup.archimedes.dataprv.protobuf.traffic.realtime.output.v1B\x1a\x44\x61taprvTrafficRealtimeDataP\x00\xaa\x02\x38PTVGroup.Flows.Protos.DataPrv.Traffic.Realtime.Output.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataprv_traffic_realtime_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nCcom.ptvgroup.archimedes.dataprv.protobuf.traffic.realtime.output.v1B\032DataprvTrafficRealtimeDataP\000\252\0028PTVGroup.Flows.Protos.DataPrv.Traffic.Realtime.Output.V1'
  _globals['_DATAPRVTRAFFICREALTIMEDATAPROTO']._serialized_start=142
  _globals['_DATAPRVTRAFFICREALTIMEDATAPROTO']._serialized_end=505
  _globals['_DATAPRVTRAFFICREALTIMEDATAPROTO_STREETTRAFFIC']._serialized_start=392
  _globals['_DATAPRVTRAFFICREALTIMEDATAPROTO_STREETTRAFFIC']._serialized_end=505
# @@protoc_insertion_point(module_scope)
